; MetaTrader 5 Configuration File
[Common]
Login=1512555287
Password=VL$?5?3k582k*
Server=FTMO-Demo
CertPassword=
NewsEnable=0
EventsEnable=0
Portable=1

[Charts]
MaxBars=5000
PrintColor=0

[Expert]
AllowDllImport=1
AllowWebRequest=1
AllowTraillingStop=1
