#!/usr/bin/env python3
"""
NANOBOT SESSION REPLAY (Last 24h)
Objective: Reconstruct signals generated by the bot in the last 24h to estimate PnL.
"""
import sys
import os
import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Add src
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.ml.stop_hunt_model import StopHuntModel

# Config
ASSETS = ["GBPUSD=X", "AUDUSD=X", "NZDUSD=X", "BTC-USD", "SOL-USD"]
RISK_PER_TRADE = 0.002 # 0.2%
CAPITAL = 10000

def get_recent_data():
    print(f"📊 FETCHING DATA FOR REPLAY (Last 2d)...")
    data = {}
    for symbol in ASSETS:
        print(f"   Downloading {symbol}...", end="\r")
        try:
            ticker = yf.Ticker(symbol)
            # Fetch 5 days to ensure enough data for indicators
            df = ticker.history(period="5d", interval="15m") 
            if not df.empty:
                data[symbol] = df
        except: pass
    return data

def calculate_indicators(df):
    try:
        df['ema_9'] = df['Close'].ewm(span=9).mean()
        df['ema_15'] = df['Close'].ewm(span=15).mean()
        df['ema_200'] = df['Close'].ewm(span=200).mean()
        
        # RSI
        delta = df['Close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / loss
        df['rsi'] = 100 - (100 / (1 + rs))
        
        # ADX (approx)
        high = df['High']; low = df['Low']; close = df['Close']
        tr1 = high - low
        tr2 = abs(high - close.shift(1))
        tr3 = abs(low - close.shift(1))
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = tr.rolling(14).mean()
        df['atr'] = atr
        
        # Simplified ADX for speed (matches live bot approximation if used)
        # Actually live bot uses full ADX logic. Let's use simplified Trend detection 
        # based on ADX>25 logic from previous script
        plus_dm = high.diff()
        minus_dm = low.diff()
        plus_dm[plus_dm < 0] = 0
        minus_dm[minus_dm > 0] = 0
        # ... full implementation too long for snippet, using mocked check or library if available
        # Let's assume standard calculation or use ATR as proxy for volatility if needed
        # Re-using the logic from compare_portfolios.py which had ADX
        
        return df
    except: return df

def simulate_session():
    data_map = get_recent_data()
    print("\n⏳ REPLAYING SESSION (Last 24h)...")
    
    signals = []
    total_pnl = 0
    wins = 0; losses = 0
    
    now = datetime.now()
    cutoff = now - timedelta(hours=24)
    # timezone aware fix
    cutoff = cutoff.astimezone() if data_map[ASSETS[0]].index.tz else cutoff
    
    # Load ML
    try:
        ml_model = StopHuntModel()
        print("   ✅ ML Model Loaded.")
    except:
        ml_model = None
        print("   ⚠️ ML Model NOT Loaded (Simulating purely technical).")
    
    for symbol, df in data_map.items():
        # Calculate Indicators
        # (Need full ADX logic here to match bot)
        # ... reusing simplified logic from `compare_portfolios.py`
        high = df['High']; low = df['Low']; close = df['Close']
        tr1 = high - low; tr2 = abs(high - close.shift(1)); tr3 = abs(low - close.shift(1))
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = tr.rolling(14).mean()
        df['atr'] = atr
        
        # RSI
        delta = close.diff()
        u = delta.clip(lower=0)
        d = -1 * delta.clip(upper=0)
        ma_u = u.ewm(com=13, adjust=False).mean()
        ma_d = d.ewm(com=13, adjust=False).mean()
        rs = ma_u / ma_d
        df['rsi'] = 100 - (100 / (1 + rs))
        
        # ADX
        plus_dm = high.diff()
        minus_dm = low.diff()
        plus_dm[plus_dm < 0] = 0
        minus_dm[minus_dm > 0] = 0
        plus_di = 100 * (plus_dm.ewm(alpha=1/14).mean() / atr)
        minus_di = abs(100 * (minus_dm.ewm(alpha=1/14).mean() / atr))
        dx = (abs(plus_di - minus_di) / abs(plus_di + minus_di)) * 100
        df['adx'] = dx.rolling(14).mean()
        
        df['ema_9'] = close.ewm(span=9).mean()
        df['ema_15'] = close.ewm(span=15).mean()
        df['ema_200'] = close.ewm(span=200).mean()
        
        # Iterate Last 24h
        try:
            # slice df to last 24h (approx 96 candles)
            # actually iterate all candles, check timestamp
            for i in range(50, len(df)-1):
                idx = df.index[i]
                # check if within last 24h (handling tz)
                # Assume utc
                if idx.timestamp() < (datetime.utcnow() - timedelta(hours=24)).timestamp():
                    continue
                    
                row = df.iloc[i]
                prev = df.iloc[i-1]
                
                # Signal Logic
                sig = 0
                if row['adx'] > 25: # Trend
                    if row['ema_9'] > row['ema_15'] and prev['ema_9'] <= prev['ema_15'] and row['Close'] > row['ema_200']: sig = 1
                    elif row['ema_9'] < row['ema_15'] and prev['ema_9'] >= prev['ema_15'] and row['Close'] < row['ema_200']: sig = -1
                else: # Range
                    if row['rsi'] < 35: sig = 1
                    elif row['rsi'] > 65: sig = -1
                    
                if sig != 0:
                    # ML Filter
                    ml_score = 0
                    if ml_model:
                        try:
                            # Mock feature extraction match
                           feat = [0, 0, 0, row['rsi'], row['adx']]
                           ml_score = ml_model.predict_proba([feat])
                        except: ml_score = 0.5
                    
                    if ml_score > 0.65: continue # Filtered
                    
                    # Trade Outcome Check
                    entry = row['Close']
                    sl = entry - (row['atr']*1.5) if sig==1 else entry + (row['atr']*1.5)
                    tp = entry + (row['atr']*2.0) if sig==1 else entry - (row['atr']*2.0) # Conservative 1:2
                    
                    # Check next candles
                    outcome = "OPEN"
                    pnl_amt = 0
                    
                    future = df.iloc[i+1:]
                    for j in range(len(future)):
                        fr = future.iloc[j]
                        if sig == 1:
                            if fr['Low'] <= sl: outcome = "LOSS"; pnl_amt = -1 * RISK_PER_TRADE * CAPITAL; break
                            if fr['High'] >= tp: outcome = "WIN"; pnl_amt = 2 * RISK_PER_TRADE * CAPITAL; break
                        else:
                            if fr['High'] >= sl: outcome = "LOSS"; pnl_amt = -1 * RISK_PER_TRADE * CAPITAL; break
                            if fr['Low'] <= tp: outcome = "WIN"; pnl_amt = 2 * RISK_PER_TRADE * CAPITAL; break
                            
                    signals.append({
                        "Time": str(idx),
                        "Asset": symbol,
                        "Type": "BUY" if sig==1 else "SELL",
                        "Outcome": outcome,
                        "PnL": pnl_amt
                    })
                    total_pnl += pnl_amt
                    if outcome == "WIN": wins += 1
                    elif outcome == "LOSS": losses += 1
                    
        except Exception as e:
            # print(e)
            pass

    print("-" * 60)
    print(f"📊 REPLAY RESULTS: Last 24 Hours")
    print("-" * 60)
    print(f"{'TIME':<20} | {'ASSET':<8} | {'TYPE':<4} | {'RES':<4} | {'PnL'}")
    
    for s in signals:
        print(f"{s['Time'][5:16]:<20} | {s['Asset']:<8} | {s['Type']:<4} | {s['Outcome']:<4} | ${s['PnL']:.2f}")
        
    print("-" * 60)
    print(f"TOTAL PnL: ${total_pnl:.2f}")
    print(f"Wins: {wins} | Losses: {losses} | Open: {len(signals)-wins-losses}")
    print("-" * 60)

if __name__ == "__main__":
    simulate_session()
